baseURL: https://vincent-lyu.netlify.app/
languageCode: en-us
title: Portfolio Website for VLYU
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      My personal site so you could learn more about me and have fun!
    title: Hello strangers, nice to see you here!
  blog: {Vicnent Lyu, always have passion in life}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vlv.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 111-2222 33334
        title: Phone (not real, don't call)
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Wow You Find Something NEW!!! 
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Copyright sololy by myself
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/master-of-beginner
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/weixin-lyu-0131/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: For More Information!
        url: blogs/abc
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: My life at lbs
        url: blogs/lbs
      - name: University at Shanghai
        url: blogs/university
      - name: Code to back test strategies
        url: blogs/program
      - name: Analyze TFL bikes
        url: blogs/bikes
      - name: Professional experience
        url: blogs/travel
      - name: Quick Glimpse of myself
        url: blogs/VincentLv_resume -LBS.pdf
    menu: Menu
    subtitle: By LWX
    title: Go back
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Life in postgraduate
        title: Postgraduate
        url: blogs/lbs     
      - image: university.jpg
        subtitle: life in undergraduate
        title: University
        url: blogs/university
      - image: code.jpg
        subtitle: Bond Strategy Performance
        title: R to caculate past performance 
        url: blogs/program
      - image: TFL bikes.jpg
        subtitle: Analyzing TFL Bikes
        title: R to analyze a problem
        url: blogs/bikes
      - image: Professional.jpg
        subtitle: My working exposure
        title: Professional Experience
        url: blogs/travel
      - image: me.jpg
        subtitle: A brief glimpse of myself
        title: My CV
        url: blogs/VincentLv_resume -LBS.pdf

  two:
    buttonText: Wants More?
    enable: yes
    subtitle: Nice to see you here. This is Vincent's website. I will continue to update my recent experience!
      If you think I am an interesting person, feel free to tax me through my email! I am always happy to make friends.  
      If you want to learn more about me, then bookmark this site! Looking forward to hearing from you!
    title: LOOK AT HERE!!!
    url: blogs/abc
